package:
  name: konf-helper
  version: 0.0.0  # Automatically determined by GitHub workflow
  epoch: 0  # Automatically determined by GitHub workflow
  description: Config sidecar for K8s
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-base
      - go

pipeline:
- name: Build
  runs: |
    mkdir -p ${{targets.destdir}}/usr/bin
    CGO_ENABLED=0 go build -o ${{targets.destdir}}/usr/bin/konf-helper ./cmd/konf-helper/main.go
 