version: '3.8'

services:
  go-test:
    image: cgr.dev/chainguard/go:latest
    command: test ./...
    working_dir: /src
    volumes:
      - .:/src
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
